# Generated by Django 3.1.2 on 2020-11-02 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201101_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите имя группы.                            Максимум 200 симоволов.', max_length=200, verbose_name='Имя')),
                ('slug', models.SlugField(help_text='Введите адрес группы.                            Максимум 50 симоволов.', unique=True, verbose_name='Адрес')),
                ('description', models.TextField(help_text='Введите описание', verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Группа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='api.group'),
        ),
    ]
