# Generated by Django 3.1.2 on 2020-11-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201102_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Введите адрес группы.                            Максимум 50 симоволов.', verbose_name='Адрес'),
        ),
    ]
